build/raveXplorer.js
src/defaultSettings.js
src/flattenData.js
src/onLayout.js
src/onLayout/applyFilters.js
src/onLayout/createNestControl.js
src/onLayout/filter.js
src/util/clone.js

Filter fixing

---

build/raveXplorer.js
src/onDraw.js
src/onLayout/drawLegend.js

Reverts RhoInc/rave-xplorer#11
@samussiah Reverting master and gonna make a v.0.1 branch to merge to. I saw you modularized onDraw and my legend changes will be really easy to add after yours, so I'll let you merge yours first.

Revert "Update legend"

---

build/raveXplorer.js
build/test-page/index.html
src/onDraw/customizeCells.js
src/onLayout/drawLegend.js

clarify and improve legend

---

build/raveXplorer.js
build/test-page/index.html
scripts/configuration.md
src/defaultSettings.js
src/defineStyles.js
src/onLayout/drawLegend.js

Closes #8 - for real this time

Experiment legend

---

build/crfheatMap.js
build/test-page/index.js
scripts/configuration.md
settings-schema.json
src/configuration/webchartsSettings.js
src/defineStyles.js
src/onDraw.js
src/onDraw/customizeRows.js
src/onDraw/dataExport/deriveData.js
src/onLayout.js
src/onLayout/addColumnControls/addResetButton.js
src/onLayout/addColumnControls/addResetButton/resetFilters.js
src/onLayout/addColumnControls/addSliders/addEventListeners.js
src/onLayout/addColumnControls/addSliders/filterData.js
src/onLayout/addColumnControls/addSliders/layout.js
src/onLayout/addColumnControls/addSliders/update.js
src/onLayout/customizeCheckboxes.js
src/onLayout/drawLegend.js

Slick sliders

---

build/crfheatMap.js
build/test-page/index.js
scripts/configuration.md
src/configuration/controlInputs.js
src/configuration/rendererSettings.js
src/configuration/webchartsSettings.js
src/defineStyles.js
src/onDraw/customizeCells.js
src/onDraw/dataExport/deriveData.js
src/onInit/summarizeData/calculateStatistics.js
src/onLayout/drawLegend.js

Freeze status

---

build/crfHeatMap.js
build/test-page/index.js
src/configuration/controlInputs.js
src/defineLayout.js
src/defineLayout/createNestControls.js
src/defineStyles.js
src/onLayout.js
src/onLayout/customizeFilters.js
src/onLayout/tweakMultiSelects.js

make subject status dropdown multi-select

---

build/crfHeatMap.js
scripts/configuration.md
settings-schema.json
src/configuration/rendererSettings.js
src/configuration/syncSettings.js
src/defineLayout.js
src/defineLayout/createNestControls.js
src/defineStyles.js
src/onDraw.js
src/onDraw/addRowDisplayToggle.js
src/onDraw/customizeCells.js
src/onLayout/customizeFilters.js
src/onLayout/tweakMultiSelects.js

add loading indicator and update settings schema

---

build/crfHeatMap.js
build/test-page/index.html
build/test-page/index.js
src/defineStyles.js
src/onDraw/addRowDisplayToggle.js
src/onDraw/customizeCells.js
src/onDraw/customizeRows.js
src/onLayout/addColumnControls/addSliders/layout.js
src/onLayout/tweakMultiSelects.js

Bootstrap conflicts

---

build/crfHeatMap.js
src/configuration/controlInputs.js

Ties into #46; still need a form-level ready-for-freeze variable.

update subject freeze status variable

---

README.md
build/crfHeatMap.js
build/test-page/index.html
build/test-page/index.js
build/test-page/rx_DataPage.csv
package.json
scripts/configuration.md
settings-schema.json
src/configuration/rendererSettings.js
src/defineLayout/createNestControls.js
src/defineStyles.js
src/init.js
src/init/checkRequiredVariables.js

Closes #67 
Closes #68 
Closes #70 
Closes #71

V1.0.1 dev

---

build/crfHeatMap.js
build/test-page/index.html
package.json
scripts/configuration.md
src/configuration/controlInputs.js
src/defineStyles.js
src/onDraw.js
src/onDraw/addRowDisplayToggle.js
src/onInit.js
src/onInit/summarizeData.js
src/onInit/summarizeData/calculateStatistics.js
src/onLayout/addColumnControls/addResetButton/resetFilters.js
src/onLayout/addColumnControls/addSliders/addEventListeners.js

Increase speed

---

build/crfHeatMap.js
build/test-page/index.html
build/test-page/index.js
package-lock.json
package.json
scripts/configuration.md
settings-schema.json
src/configuration/controlInputs.js
src/configuration/rendererSettings.js
src/configuration/syncControlInputs.js
src/configuration/syncSettings.js
src/configuration/webchartsSettings.js
src/defineStyles.js
src/onDraw.js
src/onDraw/addRowDisplayToggle.js
src/onDraw/customizeCells.js
src/onDraw/customizeRows.js
src/onDraw/dataExport/deriveData.js
src/onDraw/flagParentRows.js
src/onInit.js
src/onInit/summarizeData.js
src/onInit/summarizeData/calculateStatistics.js
src/onLayout/addColumnControls/addResetButton/resetFilters.js
src/onLayout/addColumnControls/addSliders/addEventListeners.js
src/onLayout/addColumnControls/addSliders/filterData.js
src/onLayout/customizeCheckboxes.js

Filter refactor

---

build/crfHeatMap.js
package-lock.json
package.json
scripts/configuration.md
settings-schema.json
src/onInit/summarizeData/calculateStatistics.js

CRF Heatmap v1.2.3

---

build/crfHeatMap.js
scripts/configuration.md
settings-schema.json
src/configuration/rendererSettings.js
src/configuration/syncControlInputs.js
src/configuration/syncSettings.js
src/init/checkRequiredVariables.js
src/onDraw/dataExport/deriveData.js
src/onLayout.js

#106 
#115 
- Tried to reduce the duplication of settings 
- Controls are getting a lil crowded - gonna try to pretty that up when I tackle #118

Optional settings

---

build/crfHeatMap.js
scripts/configuration.md
settings-schema.json
src/configuration/rendererSettings.js
src/configuration/syncControlInputs.js
src/configuration/syncSettings.js
src/defineLayout/createNestControls.js
src/defineLayout/createNestControls/enforceNestLogic.js
src/defineStyles.js
src/init/checkRequiredVariables.js
src/onDraw/addInfoBubbles.js
src/onDraw/dataExport/deriveData.js
src/onInit.js
src/onInit/removeFilters.js
src/onLayout.js
src/onLayout/formatControls.js

#111 
#94 
#114 
#118 
You'll recognize some code in here Spencer...

Lookin nice

---

build/crfHeatMap.js
scripts/configuration.md
settings-schema.json
src/configuration/rendererSettings.js
src/configuration/syncControlInputs.js
src/configuration/syncSettings.js
src/defineLayout/createNestControls.js
src/defineLayout/createNestControls/enforceNestLogic.js
src/defineStyles.js
src/init/checkRequiredVariables.js
src/onDraw.js
src/onDraw/addIdHover.js
src/onDraw/addInfoBubbles.js
src/onDraw/addRowDisplayToggle/onClick.js
src/onDraw/dataExport/deriveData.js
src/onInit.js
src/onInit/removeFilters.js
src/onInit/summarizeData.js
src/onInit/summarizeData/calculateStatistics.js
src/onInit/summarizeData/sortRows.js
src/onLayout.js
src/onLayout/customizeFilters.js
src/onLayout/formatControls.js
test-page/index.js

Form ordinal

---

crfHeatMap.js
src/onDestroy.js
src/wrapper.js
test-page/index.js

#135
I can't tell if my method to remove the stylesheet is too risky. I figured it'll always be the last element in the head because its being appended in the javascript but I'm interested to hear your thoughts @samussiah

add destroy

---

crfHeatMap.js
scripts/configuration.md
settings-schema.json
src/configuration/rendererSettings.js
src/configuration/syncSettings.js
src/defineStyles.js
src/onDraw/dataExport/deriveData.js
src/onInit/removeSubjectExportCols.js
src/onInit/summarizeData.js
src/onLayout/formatControls.js

Aesthetic updates

---

README.md
crfHeatMap.js
package-lock.json
package.json
scripts/configuration-markdown.js
scripts/configuration.md
settings-schema.json
src/configuration/rendererSettings.js
src/configuration/syncSettings.js
src/defineLayout/createNestControls.js
src/defineLayout/createNestControls/customizeNestOptions.js
src/defineLayout/createNestControls/customizeNestSelects.js
src/defineStyles.js
src/onDraw.js
src/onDraw/addRowDisplayToggle.js
src/onDraw/addRowDisplayToggle/iterateNest.js
src/onDraw/addRowDisplayToggle/onClick.js
src/onDraw/applyMaxWidth.js
src/onDraw/customizeRows.js
src/onDraw/dataExport/deriveData.js
src/onDraw/dataExport/xlsx.js
src/onInit/removeSubjectExportCols.js
src/onInit/summarizeData.js
src/onInit/summarizeData/sortRows.js
src/onLayout/formatControls.js
src/wrapper.js

Fix config md
